version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ip-location-api
    ports:
      - "8080:8080"
    environment:
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - CSV_FILE_PATH=data/IP2LOCATION-LITE-DB11.CSV
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s